spring:
  config:
    import: optional:secrets.yaml

  jpa:
    hibernate:
      ddl-auto: update #validate #create-drop #update
    show-sql: true
  flyway:
    baseline-on-migrate: false
springdoc:
  api-docs:
    path: /api-docs



